services:
  databroker:
    image: ghcr.io/eclipse-kuksa/kuksa-databroker:0.6.0
    container_name: kuksa_databroker
    ports:
      - "55556:55555" 

  mock:
    container_name: kuksa_mock_provider
    build:
      context: ./third_party/kuksa-mock-provider
      dockerfile: Dockerfile
    depends_on:
      - databroker
    environment:
      VDB_ADDRESS: "databroker:55555"   
     



