name: Overspeed Integration Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]


concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Show pytest markers (debug)
        run: pytest --markers || true

      - name: Run overspeed + integration tests
        run: |
          mkdir -p reports
          pytest --maxfail=1 -q -m "integration or overspeed" --junitxml=reports/it_overspeed.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: it_overspeed_report
          path: reports/it_overspeed.xml
