name: Overspeed Integration Tests
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Start Databroker + Mock Provider (docker)
      - name: Docker Compose up
        run: |
          docker compose -f docker-compose.yaml up -d
          # wait until port 55556 is ready
          for i in {1..40}; do
            nc -z 127.0.0.1 55556 && echo "Databroker ready" && break
            echo "waiting databroker..."; sleep 1
          done

      - name: Run tests (integration + overspeed)
        run: |
          mkdir -p reports
          pytest -vv --tb=short -m "integration or overspeed" \
                 --junitxml=reports/it_overspeed.xml

      - name: Teardown
        if: always()
        run: docker compose -f docker-compose.yaml down

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: it_overspeed_report
          path: reports/it_overspeed.xml
